---
- name: Update and upgrade packages for ubuntu machines
  hosts: OS_ubuntu  # Target hosts/group from inventory
  become: yes  # Execute tasks as root (sudo)
  tasks:
    - name: Update apt-get repo and cache
      ansible.builtin.apt:
        force_apt_get: yes
        cache_valid_time: 3600
        update_cache: yes  # if the apt cache is older than 1 hour, it will be updated

    - name: Update all Ubuntu packages to their latest version
      ansible.builtin.apt:
        name: "*"  # update all packages to latest version
        state: latest

    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes

- name: Verify Docker is the latest version on Ubuntu
  hosts: OS_ubuntu
  become: yes
  tasks:
    - name: Get installed Docker version
      ansible.builtin.command:
        cmd: docker --version
      register: installed_docker_version
      changed_when: false

    - name: Extract the installed Docker version number
      ansible.builtin.set_fact:
        installed_version: "{{ installed_docker_version.stdout.split(',')[0].split(' ')[2] }}"

    - name: Fetch the latest stable Docker version
      ansible.builtin.uri:
        url: "https://api.github.com/repos/docker/docker-ce/releases/latest"
        method: GET
        return_content: yes
      register: latest_docker_release

    - name: Extract the latest Docker version from the API response
      ansible.builtin.set_fact:
        latest_version: "{{ latest_docker_release.json.tag_name }}"

    - name: Compare the installed version with the latest version
      ansible.builtin.debug:
        msg: "Installed Docker version: {{ installed_version }}. Latest Docker version: {{ latest_version }}."

    - name: Ensure Docker is the latest version (if needed)
      ansible.builtin.apt:
        name: docker.io
        state: latest
      when: installed_version != latest_version


- name: Update and upgrade packages for amazon linux machines
  hosts: OS_amazon  # Target hosts/group from inventory
  become: yes  # Execute tasks as root (sudo)
  tasks:
    - name: Update yum repository cache
      ansible.builtin.yum:
        update_cache: yes

    - name: Update all Amazon Linux packages to their latest version
      ansible.builtin.yum:
        name: "*"  # update all packages to latest version
        state: latest

    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer required.
      ansible.builtin.yum:
        autoremove: yes

- name: Verify Docker is the latest version on Amazon Linux 2023
  hosts: OS_amazon
  become: yes
  tasks:
    - name: Get installed Docker version
      ansible.builtin.command:
        cmd: docker --version
      register: installed_docker_version
      changed_when: false

    - name: Extract the installed Docker version number
      ansible.builtin.set_fact:
        installed_version: "{{ installed_docker_version.stdout.split(',')[0].split(' ')[2] }}"

    - name: Fetch the latest stable Docker version
      ansible.builtin.uri:
        url: "https://api.github.com/repos/docker/docker-ce/releases/latest"
        method: GET
        return_content: yes
      register: latest_docker_release

    - name: Extract the latest Docker version from the API response
      ansible.builtin.set_fact:
        latest_version: "{{ latest_docker_release.json.tag_name }}"

    - name: Compare the installed version with the latest version
      ansible.builtin.debug:
        msg: "Installed Docker version: {{ installed_version }}. Latest Docker version: {{ latest_version }}."

    - name: Ensure Docker is the latest version (if needed)
      ansible.builtin.yum:
        name: docker
        state: latest
      when: installed_version != latest_version

- name: Report disk usage for each webserver node
  hosts: Group_webserver_node
  gather_facts: no
  tasks:
    - name: Display disk space
      shell: df -h
      register: disk_space

    - name: Debug output
      debug:
        var: disk_space.stdout_lines